### ISSUE TITLE
扩增后相机状态对状态向量的导数

### ISSUE THREAD

**Issue by Eastwind-17** [bytedance/SchurVINS#13]
![image](https://github.com/user-attachments/assets/18398343-fd1f-455d-867c-c912bcea796b)
J的第一个元素，按照MSCKF的推导应该是旋转外参，这里为什么是单位阵呢

**Comment by ouguangjun** [comment]
我猜可能是msckf扩的是相机的状态，而schurvins扩的是IMU的状态
