### ISSUE TITLE
Error occurs when running  euroc_vio_mono.launch

### ISSUE THREAD

**Issue by zy-cuhk** [bytedance/SchurVINS#2]
Hello:
     When I try to run the euroc_vio_mono.launch in your package, the error occurs: 

"terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
*** Aborted at 1712720511 (unix time) try "date -d @1712720511" if you are using GNU date ***
PC: @     0x7f8fbe5f300b gsignal
*** SIGABRT (@0x3e8001f5058) received by PID 2052184 (TID 0x7f8fae882a40) from PID 2052184; stack trace: ***
    @     0x7f8fbdc44631 (unknown)
    @     0x7f8fbeafc420 (unknown)
    @     0x7f8fbe5f300b gsignal
    @     0x7f8fbe5d2859 abort
    @     0x7f8fbe86bee6 (unknown)
    @     0x7f8fbe87df8c (unknown)
    @     0x7f8fbe87dff7 std::terminate()
    @     0x7f8fbe87e258 __cxa_throw
    @     0x7f8fbdd813f1 DBoW2::TemplatedVocabulary<>::load()
    @     0x7f8fbdd6f009 svo::loadVoc()
    @     0x7f8fbdd97e28 svo::LoopClosing::LoopClosing()
    @     0x7f8fbeaa0910 svo::factory::getLoopClosingModule()
    @     0x7f8fbea7a8f5 svo::SvoInterface::SvoInterface()
    @     0x7f8fbeaa5e11 svo_ros::SvoNodeBase::SvoNodeBase()
    @     0x55c0cff89541 main
    @     0x7f8fbe5d4083 __libc_start_main
    @     0x55c0cff895de _start
[svo-1] process has died [pid 2052184, exit code -6, cmd /home/robot/typical_packages/schurvins_ws/devel/lib/svo_ros/svo_node --v=0 __name:=svo __log:=/home/robot/.ros/log/b9fda87a-f6e3-11ee-b752-c3a6db2e312a/svo-1.log].
log file: /home/robot/.ros/log/b9fda87a-f6e3-11ee-b752-c3a6db2e312a/svo-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
" 
how to solve the problem, I sincerely wait for your reply.

**Comment by frank-fyf** [comment]
#1
