### ISSUE TITLE
some question on KITTI

### ISSUE THREAD

**Issue by zengy5** [bytedance/SchurVINS#3]
Thanks for your excellent work and this work truly helps, but I wonder if you have test this on KITTI, cause I didn't see the experiments on it in your article. I know the KITTI have some problems on IMU data, but I am curious whether it is because of IMU data or because this job is not suitable for outdoor environments. Thanks for your response, and again, thanks for your excellent work!

**Comment by frank-fyf** [comment]
the framework has  not been evaluated on kitti yet. if you need, maybe it is a valuable action item.

**Comment by zengy5** [comment]
Alright, thans for your reply.
