### ISSUE TITLE
catkin build报错

### ISSUE THREAD

**Issue by xyh2211** [bytedance/SchurVINS#5]
无论是在catkin_ws或者src目录下编译catkin build 都无法编译成功，这是为什么呢？ros用的不是很熟
显示报错误：Error：unable to find source space '/home/xyh/catkin_ws/src/src'，
![8f760c34776270dd3d21e44a00cc9fe0](https://github.com/bytedance/SchurVINS/assets/129502097/135a16d1-c5f8-4f88-9d6b-4d42f3556e8b)

**Comment by talking-toaster** [comment]
在 `/home/xyh/catkin_ws` 路径下执行 `catkin build `

**Comment by xyh2211** [comment]
不行，换到这个目录下面了，执行的时候dbow2_catkin这个编译也不报错，但是好几个小时也没有编译完成




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月17日(星期三) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytedance/SchurVINS] catkin build报错 (Issue #5)














 
在 /home/xyh/catkin_ws 路径下执行 catkin build

**Comment by ymhy1314** [comment]
你好可以参考一下这个博客https://blog.csdn.net/fanzy1234/article/details/133862395，将Dobw2的远程仓库内容直接先clone下来然后复制到build/dbow2_catkin/dbow2_src-prefix/src/dbow2_src/ 下。然后再修改一下cmakelists.txt

**Comment by ymhy1314** [comment]
你好catkin build编译过程中dbow2_catkin编译过久或者编译失败可以尝试这个办法，1）把https://github.com/dorian3d/DBoW2 clone下来，把里面的文件 复制到your_catkin_ws/build/dbow2_catkin/dbow2_src-prefix/src/dbow2_src下（dbow2_src文件夹可能要自己创建）

2）将your_catkin_ws/src/dbow2_catkin/CMakeLists.txt 中的GIT_REPOSITORY https://github.com/dorian3d/DBoW2.git 注释掉


3）重新catkin build
